{
  "formatVersion": "1.1",
  "component": {
    "group": "consumer",
    "module": "b",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "b-1.0.jar",
          "url": "b-1.0.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "b-1.0.jar",
          "url": "b-1.0.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "consumer",
          "module": "b",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "b-1.0-test-fixtures.jar",
          "url": "b-1.0-test-fixtures.jar",
          "size": 1372,
          "sha512": "9b1eec3b00ba37f2a5831cbd15752e6494fafca93836627ea697b603625df9523b846258f57d40c15c90e13b413fbbeee1c9b9af6341fd7174df0d2a280e9fc8",
          "sha256": "5613d21e9e97dff3f3aaf6f1614cd7f4401cfaf7227b8ad2104308c7a94915df",
          "sha1": "e543c37dbabbfa68e74c5351676a781db959150a",
          "md5": "b6f7f6773e0548050c016ab01e01f609"
        }
      ],
      "capabilities": [
        {
          "group": "consumer",
          "name": "b-test-fixtures",
          "version": "1.0"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "consumer",
          "module": "b",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "b-1.0-test-fixtures.jar",
          "url": "b-1.0-test-fixtures.jar",
          "size": 1372,
          "sha512": "9b1eec3b00ba37f2a5831cbd15752e6494fafca93836627ea697b603625df9523b846258f57d40c15c90e13b413fbbeee1c9b9af6341fd7174df0d2a280e9fc8",
          "sha256": "5613d21e9e97dff3f3aaf6f1614cd7f4401cfaf7227b8ad2104308c7a94915df",
          "sha1": "e543c37dbabbfa68e74c5351676a781db959150a",
          "md5": "b6f7f6773e0548050c016ab01e01f609"
        }
      ],
      "capabilities": [
        {
          "group": "consumer",
          "name": "b-test-fixtures",
          "version": "1.0"
        }
      ]
    }
  ]
}
