{
  "formatVersion": "1.1",
  "component": {
    "group": "producer",
    "module": "producer",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "producer-1.0.jar",
          "url": "producer-1.0.jar",
          "size": 1146,
          "sha512": "acedfae6bed40f33034d49f8c17067560fef09fb54ab39fd60096d320e445bf4bd6741a3eec3ec37e4788dbc18e359b92cc51aa4231d80c12d410e2949084456",
          "sha256": "6c5641a6802dc84508623188f06f231f3f9e1405e15a9f2644d959563179f5e0",
          "sha1": "e49a989580819fa0fd2f716fd46a737902ada976",
          "md5": "be3684b467ce6f089968691ce5b722f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "producer-1.0.jar",
          "url": "producer-1.0.jar",
          "size": 1146,
          "sha512": "acedfae6bed40f33034d49f8c17067560fef09fb54ab39fd60096d320e445bf4bd6741a3eec3ec37e4788dbc18e359b92cc51aa4231d80c12d410e2949084456",
          "sha256": "6c5641a6802dc84508623188f06f231f3f9e1405e15a9f2644d959563179f5e0",
          "sha1": "e49a989580819fa0fd2f716fd46a737902ada976",
          "md5": "be3684b467ce6f089968691ce5b722f1"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "producer",
          "module": "producer",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "producer-1.0-test-fixtures.jar",
          "url": "producer-1.0-test-fixtures.jar",
          "size": 1542,
          "sha512": "b30ac96f2d16ce9ed79d48937ec1e27de9ddc884fa66002e88aa67ce47073cbd1df88ccb6a2bc601038aea88407d19113686ecb0b555ab23090d214223d4b2a9",
          "sha256": "ad73005afea0e9f3266d2beb27416e0353e85b5ca2b5751c5ded5e5df3b012bc",
          "sha1": "19c8a4b25a0aca0ed0565e5396517649f91cb1b8",
          "md5": "b7d8cff0a81ce3529f72809e2652636d"
        }
      ],
      "capabilities": [
        {
          "group": "producer",
          "name": "producer-test-fixtures",
          "version": "1.0"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "consumer",
          "module": "b",
          "version": {
            "requires": "1.0"
          },
          "requestedCapabilities": [
            {
              "group": "consumer",
              "name": "b-test-fixtures"
            }
          ]
        },
        {
          "group": "producer",
          "module": "producer",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "producer-1.0-test-fixtures.jar",
          "url": "producer-1.0-test-fixtures.jar",
          "size": 1542,
          "sha512": "b30ac96f2d16ce9ed79d48937ec1e27de9ddc884fa66002e88aa67ce47073cbd1df88ccb6a2bc601038aea88407d19113686ecb0b555ab23090d214223d4b2a9",
          "sha256": "ad73005afea0e9f3266d2beb27416e0353e85b5ca2b5751c5ded5e5df3b012bc",
          "sha1": "19c8a4b25a0aca0ed0565e5396517649f91cb1b8",
          "md5": "b7d8cff0a81ce3529f72809e2652636d"
        }
      ],
      "capabilities": [
        {
          "group": "producer",
          "name": "producer-test-fixtures",
          "version": "1.0"
        }
      ]
    }
  ]
}
